theme: jekyll-theme-minimal
title: Alex Manchester
description: Alex Manchester, Mathematics, Statistics, and Computational Sciences Librarian at the Robin Li and Melissa Ma Science Library at Stanford University
